# Form implementation generated from reading ui file 'catQListWidgetItem.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets
from PyQt6.QtCore import QRect, QSize, QMetaObject
from PyQt6.QtWidgets import QWidget, QHBoxLayout, QLabel, QLineEdit, QComboBox, QApplication
import sys
import pypdftk
from PyPDF4 import PdfFileReader

class catQListWidgetItem(QWidget):
    def __init__(self, fname):
        super(catQListWidgetItem, self).__init__()
        self.setupUi(fname)

    def setupUi(self, fname):
        self.setGeometry(QRect(10, 10, 631, 23))
        self.horizontalLayout = QHBoxLayout(self)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.pdfNameLabel = QLabel(fname)
        self.horizontalLayout.addWidget(self.pdfNameLabel)
        self.pdfPasswordLineEdit = QtWidgets.QLineEdit(self)
        self.pdfPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pdfPasswordLineEdit.setPlaceholderText("Password")
        self.horizontalLayout.addWidget(self.pdfPasswordLineEdit)
        self.pagesLineEdit = QLineEdit()
        self.pagesLineEdit.setPlaceholderText("Pages")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pagesLineEdit.sizePolicy().hasHeightForWidth())
        self.pagesLineEdit.setSizePolicy(sizePolicy)
        self.pagesLineEdit.setMaximumSize(QSize(75, 16777215))
        self.horizontalLayout.addWidget(self.pagesLineEdit)
        self.selPagesComboBox = QComboBox()
        self.selPagesComboBox.setPlaceholderText("All Pages")
        self.selPagesComboBox.addItem("even")
        self.selPagesComboBox.addItem("odd")
        self.horizontalLayout.addWidget(self.selPagesComboBox)
        self.rotateComboBox = QComboBox()
        self.rotateComboBox.setPlaceholderText("Rotation")
        self.rotateComboBox.addItem("right")
        self.rotateComboBox.addItem("left")
        self.rotateComboBox.addItem("down")
        self.rotateComboBox.addItem("north")
        self.rotateComboBox.addItem("south")
        self.rotateComboBox.addItem("east")
        self.rotateComboBox.addItem("west")
        self.horizontalLayout.addWidget(self.rotateComboBox)
        self.noPagesLabel = QLabel("noPages")
        self.horizontalLayout.addWidget(self.noPagesLabel)
        # try to get number of pages using PyPDF4 library...
        try:
            with open(fname, 'rb') as pdf_file:
                self.noPagesLabel.setText(f"{PdfFileReader(pdf_file).getNumPages()} Pages")
        except:
            # If PyPDF4 library fails, try to get number of pages using pypdftk library...
            try:
                self.noPagesLabel.setText(f"{pypdftk.get_num_pages(fname)} Pages")
            except:
            # If both libs fail, 'give up'...
                self.noPagesLabel.setText("<unknown> Pages")
        self.horizontalLayout.setStretch(0, 75)
        self.horizontalLayout.setStretch(5, 10)
    
#        QMetaObject.connectSlotsByName(catQListWidgetItem)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = catQListWidgetItem('//some/file/name.pdf')
    ex.show()
    sys.exit(app.exec())